### ISSUE TITLE
Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')

### ISSUE THREAD

**Issue by hgmsq** [SpirePDF/FreeSpire.PDF#10]
![pdf报错](https://github.com/SpirePDF/FreeSpire.PDF/assets/13517103/e75807c3-000a-41fa-a3a5-f5a70332299c)
Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')

   at System.ThrowHelper.ThrowArgumentOutOfRange_IndexException()
   at sprᝅ.ᜀ(sprᝇ A_0)
   at sprᝅ.ᜁ(sprᝇ A_0)
   at sprᝅ.ᜀ(String A_0, sprᝇ A_1)
   at sprᝅ.ᜏ()
   at sprᝅ.ᜓ()
   at sprᝅ.᜙()
   at sprᝅ.᜚()
   at spr⥫.ᜆ(sprᝫ A_0)
   at spr⥫.ᜀ(sprច A_0)
   at spr⥫.᜽()
   at spr⥫.ᜍ(Boolean A_0)
   at sprᦤ.ᜀ(Graphics A_0, spr⥢ A_1, spr⧎ A_2, sprᥱ A_3, Image A_4)
   at sprᦤ.ᜁ(Int32 A_0, Int32 A_1, Int32 A_2)
   at Spire.Pdf.PdfDocumentBase.ᜀ(Int32 A_0, Int32 A_1, Int32 A_2)
   at Spire.Pdf.PdfDocumentBase.ᜀ(Int32 A_0, PdfImageType A_1, Int32 A_2, Int32 A_3)
   at Spire.Pdf.PdfDocument.SaveAsImage(Int32 pageIndex, PdfImageType type, Int32 dpiX, Int32 dpiY)
   at PdfToImage.PdfToImageConverter.PDFConvertToPNG(String pdfPath, String jpgFilePath) in

**Comment by hgmsq** [comment]
![image](https://github.com/SpirePDF/FreeSpire.PDF/assets/13517103/15cdb20e-cbbc-4303-b762-19b3850cfc95)

**Comment by eiceblue** [comment]
您好，感谢您对我们[Spire.PDF](https://www.e-iceblue.cn/Introduce/Spire-PDF-NET.html)产品的关注。请问您目前使用的是免费版本还是商业版本，如果是免费版本，我建议您先切换到商业版本（ [Spire.PDF Pack(Hot Fix)版本: 11.3.0](https://www.e-iceblue.cn/Downloads/Spire-PDF-NET.html)）测试。如果商业版本有同样的问题，请将您的测试文件发送到此邮箱support@e-iceblue.com。我们会进一步调查。提前感谢。
