### ISSUE TITLE
Setting Text on PdfTextBoxFieldWidget causes ArgumentException

### ISSUE THREAD

**Issue by calwi** [SpirePDF/FreeSpire.PDF#2]
String cannot be of zero length. (Parameter 'oldValue')

Stack Trace: 

   at System.String.Replace(String oldValue, String newValue)
   at Spire.Pdf.Widget.PdfStyledFieldWidget.get_Font()
   at Spire.Pdf.Widget.PdfStyledFieldWidget.GraphicsProperties..ctor(PdfStyledFieldWidget fieldWidget)
   at Spire.Pdf.Widget.PdfStyledFieldWidget.GetGraphicsProperties(GraphicsProperties& graphicsProperties, PdfFieldWidgetItem widgetItem)
   at Spire.Pdf.Widget.PdfTextBoxFieldWidget.ᜀ(PdfCanvas A_0, PdfFieldWidgetItem A_1)
   at Spire.Pdf.Widget.PdfTextBoxFieldWidget.ᜀ(sprᤜ A_0)
   at Spire.Pdf.Widget.PdfTextBoxFieldWidget.ᜀ(String A_0)
   at Spire.Pdf.Widget.PdfTextBoxFieldWidget.set_Text(String value)
   at Program.main(String[] argv) in

**Comment by eiceblue** [comment]
Dear Sir/Madam,

We apologize for the error you have encountered. To help us quickly provide an effective solution, please provide the following:
1. The content assigned to pdfTextBoxField.Text
2. Your PDF document

If it is not convenient to upload here, you can send the files to our support email: support@e-iceblue.com.

Additionally, we recommend upgrading to the latest version of Spire.PDF for .NET (Version: 11.3.0), which may resolve your issue. You can download it from the following link: https://www.e-iceblue.com/Download/download-pdf-for-net-now.html.

Sincerely,
E-iceblue support team
